services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-contactos-app
    ports:
      - "8090:8000"
    env_file:
      - .env  # Carga las variables de entorno desde el archivo .env
    network_mode: "host"  # Usa el modo de red host