"""Corregir relaciones en modelos

Revision ID: 4c244c1ed003
Revises: fc2704541b8e
Create Date: 2025-04-23 18:45:54.760121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c244c1ed003'
down_revision: Union[str, None] = 'fc2704541b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
