"""Se agrega nuevos campos en cuenta

Revision ID: 7dff8b59ef32
Revises: c627f4d4ce6b
Create Date: 2025-04-27 01:29:49.158487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dff8b59ef32'
down_revision: Union[str, None] = 'c627f4d4ce6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuenta', sa.Column('creado_at', sa.DateTime(), nullable=True))
    op.add_column('cuenta', sa.Column('eliminado', sa.Boolean(), nullable=True))
    op.add_column('cuenta', sa.Column('total_mensajes_enviados', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuenta', 'total_mensajes_enviados')
    op.drop_column('cuenta', 'eliminado')
    op.drop_column('cuenta', 'creado_at')
    # ### end Alembic commands ###
