"""Actualizar modelos

Revision ID: bc7c76b4d09e
Revises: ef8dbf68909d
Create Date: 2025-04-23 17:54:47.580634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7c76b4d09e'
down_revision: Union[str, None] = 'ef8dbf68909d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_etiqueta_cuenta_id_fkey', 'chat_etiqueta', type_='foreignkey')
    op.drop_constraint('chat_etiqueta_etiqueta_id_fkey', 'chat_etiqueta', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('chat_etiqueta_etiqueta_id_fkey', 'chat_etiqueta', 'etiqueta', ['etiqueta_id'], ['id'])
    op.create_foreign_key('chat_etiqueta_cuenta_id_fkey', 'chat_etiqueta', 'cuenta', ['cuenta_id'], ['id'])
    # ### end Alembic commands ###
