"""Crear tablas iniciales

Revision ID: c627f4d4ce6b
Revises: 
Create Date: 2025-04-23 21:13:53.299302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c627f4d4ce6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cuenta', sa.String(), nullable=True),
    sa.Column('instancia_evolution', sa.String(), nullable=True),
    sa.Column('numero_corporativo', sa.String(), nullable=True),
    sa.Column('numero_personal', sa.String(), nullable=True),
    sa.Column('nombre_personal', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuenta_id'), 'cuenta', ['id'], unique=False)
    op.create_table('cabecera_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bloqueado_at', sa.DateTime(), nullable=True),
    sa.Column('numero_de_contacto', sa.String(), nullable=True),
    sa.Column('intentos_maliciosos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabecera_chat_id'), 'cabecera_chat', ['id'], unique=False)
    op.create_table('etiqueta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id', 'cuenta_id')
    )
    op.create_table('chat_etiqueta',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['cabecera_chat.id'], ),
    sa.ForeignKeyConstraint(['etiqueta_id', 'cuenta_id'], ['etiqueta.id', 'etiqueta.cuenta_id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'etiqueta_id', 'cuenta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_etiqueta')
    op.drop_table('etiqueta')
    op.drop_index(op.f('ix_cabecera_chat_id'), table_name='cabecera_chat')
    op.drop_table('cabecera_chat')
    op.drop_index(op.f('ix_cuenta_id'), table_name='cuenta')
    op.drop_table('cuenta')
    # ### end Alembic commands ###
