"""Inicializar modelos

Revision ID: ef8dbf68909d
Revises: 
Create Date: 2025-04-23 11:34:15.338575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8dbf68909d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etiqueta', 'cuenta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_etiqueta_id', table_name='etiqueta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_etiqueta_id', 'etiqueta', ['id'], unique=False)
    op.alter_column('etiqueta', 'cuenta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
