"""Corregir claves foráneas en chat_etiqueta

Revision ID: fc2704541b8e
Revises: bc7c76b4d09e
Create Date: 2025-04-23 18:19:24.961187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2704541b8e'
down_revision: Union[str, None] = 'bc7c76b4d09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_etiqueta', 'etiqueta', ['etiqueta_id'], ['id'])
    op.create_foreign_key(None, 'chat_etiqueta', 'cuenta', ['cuenta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_etiqueta', type_='foreignkey')
    op.drop_constraint(None, 'chat_etiqueta', type_='foreignkey')
    # ### end Alembic commands ###
